import "../globals.css"
import { AuthProvider } from "@/app/(app)/osobni_zona/(context)/AuthContext";
import Shell from "@/app/(app)/osobni_zona/(parent_components)/shell";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <AuthProvider>
        <body>
        <Shell>{children}</Shell>
        </body>
      </AuthProvider>
      </html>
  )
}
