import "../globals.css"
import {CSPostHogProvider} from "@/app/providers";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <CSPostHogProvider>
            <body>
            {children}
            </body>
        </CSPostHogProvider>
        </html>
    )
}
