import './globals.css'
import {Head} from "next/document";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="cs">
    <Head>
      <title>Autoškola Test - vše o testech z autoškoly přehledně</title>
      <meta name="description" content="Na stránce autoškolatest.cz se dozvíte veškeré potřebné informace o testu teorie v autoškole." />
      <meta name="author" content="Jakub Záloha" />
      <meta name="keywords" content="autoškola test, autoškola testy, testy z autoškoly, testy řidičák" />
    </Head>
      <body>{children}</body>
    </html>
  )
}
